=== marlenesv/40260/xml00/alumnos.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="alumnos">
        <xs:complexType> 
            <xs:sequence>
                <xs:element name="alumno" maxOccurs="unbounded">
                    <xs:complexType>
                    <xs:sequence>
                        <xs:element name="nombre" type="xs:string"></xs:element>
                        <xs:element name="nacimiento" type="xs:date"></xs:element>
                    </xs:sequence>
                        <xs:attribute name="correo"></xs:attribute>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== marlenesv/40260/xml00/alumnos.xml
<alumnos xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="alumnos.xsd"
<alumnos>
    <alumno>
        <nombre>Mar</nombre>
        <nacimiento>30/abril/2005</nacimiento>
    </alumno>
    <alumno>
        <nombre>Mario</nombre>
        <nacimiento>27/abril/2005</nacimiento>
    </alumno>
</alumnos>
