<?xml version="1.0"?>
<!DOCTYPE alumnos [
    <!ELEMENT alumnos (alumno*)>
    <!ELEMENT alumno (nombre, apellido, curso)>
    <!ELEMENT nombre (#PCDATA)>
    <!ELEMENT apellido (#PCDATA)>
    <!ELEMENT curso (#PCDATA)>

    <!ATTLIST alumno 
        id ID #REQUIRED
        edad CDATA #IMPLIED
        becado (si|no) "no">
]>

<alumnos>
    <alumno id="1" edad="18" becado="si">
        <nombre>Edder</nombre>
        <apellido>Landa</apellido>
        <curso>5ยบ Bachillerato</curso>
    </alumno>

    <alumno id="2" edad="19" becado="si">
        <nombre>Camila</nombre>
        <apellido>Perez</apellido>
        <curso>2ยบ Bachillerato</curso>
    </alumno>

    <alumno id="3" edad="18" becado="no">
        <nombre>Ana</nombre>
        <apellido>Reyes</apellido>
        <curso>3ยบ Bachillerato</curso>
    </alumno>
</alumnos>